from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Protocol

from harness.context_budget import TokenBudgeter


EXTRACTIVE_COMPRESSION_METHOD = "extractive_line_window"
EXTRACTIVE_COMPRESSION_VERSION = "harness.context_compression.extractive/v1"
COMPRESSION_MARKER = "\n[COMPRESSED: deterministic extractive context]\n"
_TERM_RE = re.compile(r"[A-Za-z0-9_./:-]+")
_DEFINITION_RE = re.compile(r"^\s*(class|def|async\s+def|function|const|let|var|export|import|from)\b")
_BOILERPLATE_PREFIXES = (
    "copyright ",
    "all rights reserved",
    "generated by ",
    "do not edit",
)
_INELIGIBLE_KINDS = {
    "harness_vocabulary",
    "builtin_harness_domain",
    "security_policy_summary",
    "sandbox_profiles",
    "request_context",
    "memory_summary",
    "git_status",
    "git_diff_stat",
    "git_diff",
    "recent_artifacts",
}
_WARNING_CODES = {
    "memory_not_authority",
    "untrusted_repo_context",
    "artifact_content_not_authority",
    "generated_text_not_authority",
    "artifact_body_not_indexed",
}


@dataclass(frozen=True)
class CompressedContextBlock:
    content: str
    token_count: int
    original_token_count: int
    compressed: bool
    lineage: dict[str, Any] = field(default_factory=dict)


class ContextCompressor(Protocol):
    def compress(
        self,
        block: Any,
        *,
        query: str,
        target_tokens: int,
        budgeter: TokenBudgeter,
    ) -> CompressedContextBlock:
        ...


class ExtractiveContextCompressor:
    method = EXTRACTIVE_COMPRESSION_METHOD
    version = EXTRACTIVE_COMPRESSION_VERSION

    def is_eligible(self, block: Any) -> bool:
        if getattr(block, "role", None) != "retrieved":
            return False
        if getattr(block, "kind", None) in _INELIGIBLE_KINDS:
            return False
        retrieval = getattr(block, "retrieval", None) or {}
        if not retrieval:
            return False
        warnings = set(str(warning) for warning in retrieval.get("warnings") or [])
        if "memory_not_authority" in warnings:
            return False
        source_kind = str(retrieval.get("source_kind") or "")
        if source_kind not in {"repo_file"}:
            return False
        return True

    def compress(
        self,
        block: Any,
        *,
        query: str,
        target_tokens: int,
        budgeter: TokenBudgeter,
    ) -> CompressedContextBlock:
        original = str(getattr(block, "content", ""))
        original_tokens = budgeter.count(original)
        if target_tokens <= 0 or not self.is_eligible(block):
            return CompressedContextBlock(
                content=original,
                token_count=original_tokens,
                original_token_count=original_tokens,
                compressed=False,
            )
        if original_tokens <= target_tokens:
            return CompressedContextBlock(
                content=original,
                token_count=original_tokens,
                original_token_count=original_tokens,
                compressed=False,
            )
        extracted = _extract_lines(original, query=query)
        if not extracted:
            extracted = _dedupe_non_boilerplate_lines(original.splitlines())[:12]
        content = COMPRESSION_MARKER + "\n".join(extracted).strip()
        fit = budgeter.fit(content, target_tokens, marker="\n[TRUNCATED: compressed context budget]\n")
        compressed_content = _preserve_warning_lines(original, fit.text)
        while budgeter.count(compressed_content) > target_tokens and compressed_content:
            fit = budgeter.fit(compressed_content, target_tokens, marker="\n[TRUNCATED: compressed context budget]\n")
            compressed_content = fit.text
        line_count = len(original.splitlines())
        selected_lines = _selected_line_numbers(original, extracted)
        return CompressedContextBlock(
            content=compressed_content,
            token_count=budgeter.count(compressed_content),
            original_token_count=original_tokens,
            compressed=True,
            lineage={
                "schema_version": self.version,
                "method": self.method,
                "version": self.version,
                "original_token_count": original_tokens,
                "compressed_token_count": budgeter.count(compressed_content),
                "original_line_count": line_count,
                "selected_lines": selected_lines,
                "original_chunk_ids": list(getattr(block, "chunk_ids", None) or []),
                "provenance_ids": [getattr(block, "provenance_id", None)] if getattr(block, "provenance_id", None) else [],
                "permission_granting": False,
                "policy_authority": False,
                "approval_authority": False,
            },
        )


def _extract_lines(text: str, *, query: str) -> list[str]:
    lines = text.splitlines()
    query_terms = set(_terms(query))
    selected_indexes: set[int] = set()
    for index, line in enumerate(lines):
        lowered = line.lower()
        line_terms = set(_terms(line))
        if query_terms and query_terms & line_terms:
            selected_indexes.update(_window(index, len(lines), radius=2))
        elif _DEFINITION_RE.search(line):
            selected_indexes.add(index)
    if not selected_indexes:
        selected_indexes.update(range(min(12, len(lines))))
    ordered = [lines[index] for index in sorted(selected_indexes)]
    return _dedupe_non_boilerplate_lines(ordered)


def _dedupe_non_boilerplate_lines(lines: list[str]) -> list[str]:
    selected: list[str] = []
    seen: set[str] = set()
    for line in lines:
        stripped = line.rstrip()
        normalized = stripped.strip().lower()
        if not stripped:
            if selected and selected[-1] != "":
                selected.append("")
            continue
        if any(normalized.startswith(prefix) for prefix in _BOILERPLATE_PREFIXES):
            continue
        if normalized in seen:
            continue
        seen.add(normalized)
        selected.append(stripped)
    while selected and selected[-1] == "":
        selected.pop()
    return selected


def _preserve_warning_lines(original: str, compressed: str) -> str:
    warning_lines = [
        line
        for line in original.splitlines()
        if any(code in line for code in _WARNING_CODES)
    ]
    if not warning_lines:
        return compressed
    result = compressed.rstrip()
    for line in warning_lines:
        if line not in result:
            result += f"\n{line}"
    return result


def _selected_line_numbers(original: str, selected: list[str]) -> list[int]:
    remaining = list(selected)
    numbers: list[int] = []
    for index, line in enumerate(original.splitlines(), start=1):
        if remaining and line.rstrip() == remaining[0].rstrip():
            numbers.append(index)
            remaining.pop(0)
    return numbers


def _terms(text: str) -> list[str]:
    terms: list[str] = []
    seen: set[str] = set()
    for token in _TERM_RE.findall(text.lower()):
        for part in re.split(r"[/.\-:]+", token):
            if part and part not in seen:
                seen.add(part)
                terms.append(part)
        if token and token not in seen:
            seen.add(token)
            terms.append(token)
    return terms


def _window(index: int, size: int, *, radius: int) -> set[int]:
    return set(range(max(0, index - radius), min(size, index + radius + 1)))
