from __future__ import annotations

from pathlib import Path
from pprint import pformat
from shutil import copyfile
from typing import Any


TUI_HOME_IMAGE_SCHEMA_VERSION = "harness.tui_home_image/v1"
DEFAULT_TUI_PIXEL_ART_WIDTH = 80
DEFAULT_TUI_HOME_SOURCE = Path("assets/tui/home_source.png")
DEFAULT_TUI_PIXEL_ART_MODULE = Path("src/harness/tui_assets/pixel_art.py")

FORBIDDEN_TUI_IMAGE_PATH_PARTS = {".harness", ".git", "secrets"}
FORBIDDEN_TUI_IMAGE_SUFFIXES = {".pem", ".key", ".sqlite"}
SUPPORTED_TUI_IMAGE_SUFFIXES = {".bmp", ".gif", ".jpeg", ".jpg", ".png", ".webp"}


class TuiHomeImageError(ValueError):
    pass


def set_tui_home_image(
    image_path: Path,
    *,
    width: int = DEFAULT_TUI_PIXEL_ART_WIDTH,
    source_path: Path = DEFAULT_TUI_HOME_SOURCE,
    output_path: Path = DEFAULT_TUI_PIXEL_ART_MODULE,
) -> dict[str, Any]:
    """Import an explicit local image and regenerate static TUI terminal art."""

    source_image = resolve_tui_image_path(image_path)
    if width < 16 or width > 120:
        raise TuiHomeImageError("TUI home image width must be between 16 and 120 cells.")

    try:
        from PIL import Image
    except ImportError as exc:
        raise TuiHomeImageError(
            "Pillow is required only for importing TUI home images. "
            "Install it locally with: python3 -m pip install Pillow"
        ) from exc

    try:
        with Image.open(source_image) as image:
            image.verify()
    except Exception as exc:
        raise TuiHomeImageError(f"TUI home image could not be opened: {exc}") from exc

    source_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    copyfile(source_image, source_path)
    generated = generate_tui_pixel_art_module(
        source_path=source_path,
        output_path=output_path,
        width=width,
    )
    return {
        "schema_version": TUI_HOME_IMAGE_SCHEMA_VERSION,
        "ok": True,
        "source_image": str(source_image),
        "stored_source": str(source_path),
        "generated_module": str(output_path),
        "width": generated["width"],
        "height": generated["height"],
        "terminal_rows": generated["terminal_rows"],
        "errors": [],
    }


def generate_tui_pixel_art_module(
    *,
    source_path: Path = DEFAULT_TUI_HOME_SOURCE,
    output_path: Path = DEFAULT_TUI_PIXEL_ART_MODULE,
    width: int = DEFAULT_TUI_PIXEL_ART_WIDTH,
) -> dict[str, int]:
    try:
        from PIL import Image
    except ImportError as exc:
        raise TuiHomeImageError(
            "Pillow is required only for regenerating TUI pixel art. "
            "Install it locally with: python3 -m pip install Pillow"
        ) from exc

    if not source_path.exists():
        raise TuiHomeImageError(f"Missing source image: {source_path}")

    image = Image.open(source_path).convert("RGB")
    source_width, source_height = image.size
    target_height = round(source_height / source_width * width)
    if target_height % 2:
        target_height += 1
    image = image.resize((width, target_height), Image.Resampling.NEAREST)

    rows: list[list[tuple[str, str]]] = []
    for y in range(0, target_height, 2):
        row: list[tuple[str, str]] = []
        for x in range(width):
            foreground = _hex_rgb(image.getpixel((x, y)))
            background = _hex_rgb(image.getpixel((x, y + 1)))
            row.append((foreground, background))
        rows.append(row)

    output_path.write_text(
        "from __future__ import annotations\n\n"
        "# Generated by harness.tui_assets.art.\n"
        "# Each tuple is (foreground, background) for one upper-half block cell.\n"
        f"# Do not edit by hand; regenerate from {source_path.as_posix()}.\n\n"
        f"TUI_PIXEL_ART_HALF_BLOCKS = {pformat(rows, width=120)}\n",
        encoding="utf-8",
    )
    return {"width": width, "height": target_height, "terminal_rows": len(rows)}


def resolve_tui_image_path(path: Path) -> Path:
    expanded = path.expanduser()
    _reject_symlink_components(expanded)
    resolved = expanded.resolve()
    _validate_tui_image_path(resolved)
    if not resolved.exists():
        raise TuiHomeImageError(f"TUI home image does not exist: {resolved}")
    if not resolved.is_file():
        raise TuiHomeImageError(f"TUI home image path is not a file: {resolved}")
    if resolved.suffix.lower() not in SUPPORTED_TUI_IMAGE_SUFFIXES:
        raise TuiHomeImageError(f"Unsupported TUI home image extension: {resolved.suffix or '<none>'}")
    return resolved


def _hex_rgb(rgb: tuple[int, int, int]) -> str:
    return "#{:02x}{:02x}{:02x}".format(*rgb)


def _validate_tui_image_path(path: Path) -> None:
    _reject_symlink_components(path)
    if any(part in FORBIDDEN_TUI_IMAGE_PATH_PARTS for part in path.parts):
        raise TuiHomeImageError("TUI home image path is forbidden by harness safety policy.")
    if path.name.startswith(".env"):
        raise TuiHomeImageError("TUI home image path is forbidden by harness safety policy.")
    if path.suffix.lower() in FORBIDDEN_TUI_IMAGE_SUFFIXES:
        raise TuiHomeImageError("TUI home image path is forbidden by harness safety policy.")


def _reject_symlink_components(path: Path) -> None:
    current = Path(path.anchor) if path.is_absolute() else Path(".")
    parts = path.parts
    start = 1 if path.is_absolute() else 0
    for part in parts[start:]:
        current = current / part
        if current.is_symlink():
            raise TuiHomeImageError("TUI home image path cannot include symlinks.")
